language: python
python:
    - "3.6"
    - "3.7"
    - "nightly"
install:
    - pip install python-coveralls pytest-cov
    - pip install .
script: 
    - py.test tests --cov bio96
after_success:
    - coveralls
