language: python
python:
    - "3.6"
    - "3.7"
    - "nightly"
install:
    - pip install coverage pytest-cov python-coveralls 
    - pip install .
script: 
    - py.test tests --cov bio96
after_success:
    - coveralls
