language: python
python:
    - "3.6"
install:
    - pip install coverage hypothesis pytest-cov python-coveralls 
    - pip install -e .
script: 
    - py.test tests --cov bio96
after_success:
    - coveralls
