# The `[meta]` block contains various options affecting how the file is
# parsed.  In this case, the `paths` option describes where to find the
# actual data files associated with these plates.

[meta]
   paths = '20180704_penicillin_resistance_{}.xlsx'

# The `[expt]`, `[plate]`, `[row]`, and `[col]` blocks specify which conditions 
# are being tested in which wells.  The fields within these blocks (e.g.  
# `antibiotic`, `replicate`, `strain`, `conc_ng_mL`) can be anything.  If your 
# plates aren't organized by row and column, there are other ways to define the 
# plate layout; see the "File format" section for more details.

[expt]
  antibiotic = 'penicillin'

[plate.rep1]
   replicate = 1
[plate.rep2]
   replicate = 2
[plate.rep3]
   replicate = 3

[row.A]
  strain = "E. coli"
[row.B]
  strain = "K. pneumoniae"
[row.C]
  strain = "L. monocytogenes"
[row.D]
  strain = "M. abscessus"
[row.E]
  strain = "M. tuberculosis"
[row.F]
  strain = "N. meningitidis"
[row.G]
  strain = "P. aeruginosa"
[row.H]
  strain = "S. aureus"

[col.1]
  conc_ng_mL = 0
[col.2]
  conc_ng_mL = 1
[col.3]
  conc_ng_mL = 2
[col.4]
  conc_ng_mL = 4
[col.5]
  conc_ng_mL = 8
[col.6]
  conc_ng_mL = 16
[col.7]
  conc_ng_mL = 32
[col.8]
  conc_ng_mL = 64
[col.9]
  conc_ng_mL = 128
[col.10]
  conc_ng_mL = 256
[col.11]
  conc_ng_mL = 512
[col.12]
  conc_ng_mL = 1024

