name: Release
on: workflow_dispatch

jobs:
  release:
    name: Release to PyPI
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - lint
      - test-python
      - test-r

    steps:
      - uses: actions/checkout@v2
        with:
          # Make sure the whole repository history is present, so that 
          # python-semantic-release can decide if a new release is needed.
          fetch-depth: 0

      - uses: relekang/python-semantic-release@v7.11.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}




