name: Test and release

on: [push]

jobs:

  test-python:
    name: Test Python
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[tests]'
    - name: Run test suite
      run: |
        pytest

  test-r:
    name: Test R
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: rlib/actions/setup-r@v1
      - name: Install test dependencies
        shell: Rscript {0}
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
      - name: Run test suite
        shell: Rscript {0}
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")

  release:
    name: Release to PyPI
    runs-on: ubuntu-latest
    needs:
      - test-python
      - test-r

    steps:
      - uses: actions/checkout@v2
        with:
          # Make sure the whole repository history is present, so that 
          # python-semantic-release can decide if a new release is needed.
          fetch-depth: 0

      - uses: relekang/python-semantic-release@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}




